---
- name: New network fitlers
  hosts: localhost
  connection: local

  tasks:
    - name: Select 50th usable address from provided subnet 192.168.1.1/50
      debug: msg="{{ '192.168.1.1/24' | next_nth_usable(50) }}"

    - name: Validate subnet membership
      debug: msg="{{ '192.168.1.1/24' | network_in_network('192.168.1.1/25') }}"


