---
- name: Two new tests introduced
  hosts: localhost
  connection: local

  vars: 
    list_one:
      - 1
      - 3 == 3
      - True
    list_two:
      - False
      - True
    list_three:
      - False
      - False

  tasks:
    - name: All test list_one (1, 3 == 3, True)
      debug: msg="list_one are True"
      when: list_one is all

    - name: All test list_two (False, True)
      debug: msg="list_two are True"
      when: list_two is all

    - name: Any test list_one (1, 3 == 3, True)
      debug: msg="list_one are True"
      when: list_one|any

    - name: Any test list_three (False, False)
      debug: msg="list_two are True"
      when: list_three is any


