---
- name: Include vaults with two different credentials
  hosts: localhost
  connection: local

  tasks:
    - name: Load cloud vars from vault
      include_vars:
        name: cloud
        file: vault_cloud_vars

    - name: Load app vars from vault
      include_vars:
        name: app
        file: vault_app_vars

